
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in an project.

== Configuration

This plugin relies on the {link_griffon_datasource_plugin}. Please follow the instructions to configure this plugin first.

The plugin's <<_modules, module>> registers a `{api_sql2o_handler}` helper class that defines the base contract
for accessing a datasource and issue SQL queries to it. This class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.sql2o.Sql2oHandler.java
----
include::{path_griffon_sql2o_core}/src/main/java//griffon/plugins/sql2o/Sql2oHandler.java[tags=methods,indent=0]
----

These method are aware of multiple datasources. If no datasourceName is specified when calling them then the default
datasource will be selected. You can inject an instance of this class anywhere it's needed using `@Inject`. There is one
callback you may use with this method: `{api_sql2o_callback}`.

This callback is defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.sql2o.Sql2oCallback.java
----
include::{path_griffon_sql2o_core}/src/main/java/griffon/plugins/sql2o/Sql2oCallback.java[lines=25..-1]
----

=== Bootstrap

You may execute arbitrary database calls during connection and disconnection from a datasource. Simply
create a class that implements the `{api_sql2o_bootstrap}` interface and register it within a module, for example

[source,java,options="nowrap"]
.src/main/groovy/com/acme/SampleSql2oBootstrap.groovy
----
package com.acme

import griffon.plugins.sql2o.Sql2oBootstrap
import org.sql2o.Sql2o

import javax.annotation.Nonnull
import javax.inject.Named

@Named("sample")
class SampleSql2oBootstrap implements Sql2oBootstrap {
    @Override
    void init(@Nonnull String datasourceName, @Nonnull Sql2o sql2o) {
        // operations after first connection to datasource
    }

    @Override
    void destroy(@Nonnull String datasourceName, @Nonnull Sql2o sql2o) {
        // operations before disconnecting from the datasource
    }
}
----

[source,java,options="nowrap"]
.src/main/java/com/acme/ApplicationModule.java
----
package com.acme;

import griffon.plugins.sql2o.Sql2oBootstrap;
import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(Sql2oBootstrap.class)
            .to(SampleSql2oBootstrap.class)
            .asSingleton();
    }
}
----

== Example

The following is a trivial usage of the `{api_sql2o_handler}` inside a Java service

[source,java,options="nowrap"]
.com.acme.SampleService.java
----
package com.acme;

import griffon.core.artifact.GriffonService;
import griffon.metadata.ArtifactProviderFor;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonService;

import griffon.plugins.sql2o.Sql2oHandler;
import griffon.plugins.sql2o.Sql2oCallback;
import org.sql2o.Sql2o;
import org.sql2o.StatementRunnableWithResult;

import javax.inject.Inject;

@ArtifactProviderFor(GriffonService.class)
public class SampleService {
    @Inject
    private Sql2oHandler sql2oHandler

    public Person findById(final int id) {
        return sql2oHandler.withSql2o(new Sql2oCallback<Person>() {
            @Override
            Person handle(@Nonnull String datasourceName, @Nonnull Sql2o sql2o) {
                return (Person) sql2o.withConnection(new StatementRunnableWithResult() {
                    @Override
                    Object run(Connection connection, Object argument) throws Throwable {
                        List<Person> people = connection.createQuery("SELECT * FROM person WHERE id = :id")
                            .addParameter("id", id)
                            .executeAndFetch(Person.class);
                        return people != null && people.size() > 0 ? people.get(0) : null;
                    }
                })
            }
        })
    }
}
----

Here's the Groovy version of it

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor

import griffon.plugins.sql2o.Sql2oHandler
import org.sql2o.Sql2o
import org.sql2o.StatementRunnableWithResult

import javax.inject.Inject

@ArtifactProviderFor(GriffonService)
class SampleService {
    @Inject
    private Sql2oHandler sql2oHandler

    Person findById(final int id) {
         sql2oHandler.withSql2o { String datasourceName, Sql2o sql2o ->
             sql2o.withConnection({ connection, arg ->
                 connection.createQuery('SELECT * FROM person WHERE id = :id')
                         .addParameter('id', id)
                         .executeAndFetch(Person)[0]
             } as StatementRunnableWithResult)
         }
    }
}
----

== Events

The following events will be triggered by `{api_sql2o_handler}`

Sql2oConnectStart(String datasourceName, Map<String, Object> config):: Triggered before connecting to the datasource.
Sql2oConnectEnd(String datasourceName, Map<String, Object> config, Sql2o sql2o):: Triggered after connecting to the datasource.
Sql2oDisconnectStart(String datasourceName, Map<String, Object> config, Sql2o sql2o):: Triggered before disconnecting from the datasource.
Sql2oDisconnectEnd(String datasourceName, Map<String, Object> config):: Triggered after disconnecting from the datasource.

NOTE: DataSource events may be triggered during connection and disconnection from a datasource.

== AST Transformation

You can apply the `{api_sql2o_aware}` AST transformation on any class. This injects the behavior of `{api_sql2o_handler}`
into said class. The previous Groovy service example can be rewritten as follows

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor
import griffon.transform.Sql2oAware

import org.sql2o.Sql2o
import org.sql2o.StatementRunnableWithResult

@Sql2oAware
@ArtifactProviderFor(GriffonService)
class SampleService {
    Person findById(final int id) {
         sql2oHandler.withSql2o { String datasourceName, Sql2o sql2o ->
             sql2o.withConnection({ connection, arg ->
                 connection.createQuery('SELECT * FROM person WHERE id = :id')
                         .addParameter('id', id)
                         .executeAndFetch(Person)[0]
             } as StatementRunnableWithResult)
         }
    }
}
----

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-sql2o-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_sql2o.dsld
 * gdsl/griffon_sql2o.gdsl
